name: roxctl

on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: endpoint of Central to use in format https://<endpoint>
        required: true
        default: ''

jobs:
  roxctl:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
      runs-on: ${{ matrix.os }}
      permissions:
        id-token: write # Required for Central Login
      steps:
        - name: Configure Central creds for the job
          uses: stackrox/central-login@v1.0.2
          with:
            endpoint: ${{ inputs.endpoint }}
            skip-tls-verify: true
        - name: Setup roxctl by downloading it from Central to match version
          uses: stackrox/roxctl-installer-action@v1.1.2
          with:
            central-endpoint: ${{ env.ROX_ENDPOINT }}
            central-token: ${{ env.ROX_API_TOKEN }}
            skip-tls-verify: true

        - name: whoami
          shell: bash
          run: |
            roxctl central whoami
